CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: Build Website
+name: Build notebooks and publish
 
 on:
   workflow_dispatch:
@@ -11,68 +11,77 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
-env:
-  NPROC: '2'       # Number of Julia processes to run the notebooks
-  JULIA_CACHE: '1' # Set this env var zero to disable caching
-  JULIA_CONDAPKG_BACKEND: 'Null'  # Use system python for PythonCall.jl
-  GKSwstype: 100
-  JULIA_NUM_THREADS: 'auto'
-  PY_VER: '3.11'
+permissions:
+  packages: write
 
+env:
+  NPROC: '2'                      # Number of Julia processes to run the notebooks
 
 jobs:
-  CI:
+  setup:
     runs-on: ubuntu-latest
+    outputs:
+      hash: ${{ steps.hash.outputs.id }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
-      - name: Setup Python ${{ env.PY_VER }}
-        uses: actions/setup-python@v4
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
         with:
-          python-version: ${{ env.PY_VER }}
-          cache: 'pip'
-          cache-dependency-path: |
-            requirements.txt
-      - name: Install Python dependencies
-        run: pip install -r requirements.txt
-      - name: Read Julia version
-        id: read_toml
-        uses: SebRollen/toml-action@v1.0.2
+          registry: ghcr.io
+          username: ${{ github.repository_owner	}}
+          password: ${{ github.token	}}
+      - name: Get docker image hash
+        id: hash
+        run: echo "id=${{ hashFiles('requirements.txt', 'Project.toml', 'Manifest.toml', 'src/**', '.github/Dockerfile') }}" >> "$GITHUB_OUTPUT"
+      - name: Build and cache Docker container
+        uses: docker/build-push-action@v4
         with:
-          file: 'Manifest.toml'
-          field: 'julia_version'
-      - name: Setup Julia
-        uses: julia-actions/setup-julia@v1
-        with:
-          version: ${{ steps.read_toml.outputs.value }}
-      - name: Restore Julia dependencies
-        id: restore-cache
-        uses: actions/cache/restore@v3
-        if: ${{ env.JULIA_CACHE != '0'}}
-        with:
-          path: |
-            ~/.julia
-          key: ${{ runner.os }}-julia-${{ env.JULIA_CACHE }}-${{ hashFiles('**/Manifest.toml') }}
-          # restore-keys: |
-          #   ${{ runner.os }}-julia-${{ env.JULIA_CACHE }}-
-      - name: Install Julia dependencies
-        shell: julia --project=@. --color=yes {0}
-        run: |
-          import Pkg
-          Pkg.Registry.update()
-          Pkg.instantiate()
-          Pkg.resolve()
-          Pkg.precompile()
-          Pkg.gc()
-      - name: Save Julia dependencies
-        uses: actions/cache/save@v3
-        if: ${{ steps.restore-cache.outputs.cache-hit != 'true' && env.JULIA_CACHE != '0' }}
-        with:
-          path: |
-            ~/.julia
-          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
+          context: .
+          file: '.github/Dockerfile'
+          tags: ghcr.io/${{ github.repository }}:${{ steps.hash.outputs.id }}
+          push: true
+          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ steps.hash.outputs.id }}
+          cache-to: type=inline
+
+  execute:
+    runs-on: ubuntu-latest
+    needs: setup
+    container:
+      image: ghcr.io/${{ github.repository }}:${{ needs.setup.outputs.hash }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
       - name: Build notebooks with ${{ env.NPROC }} processes
         run: JULIA_PROJECT=@. julia --color=yes -p ${{ env.NPROC }} literate.jl
+      - name: Upload Notebook
+        uses: actions/upload-artifact@v3
+        with:
+          name: notebooks
+          path: docs
+          retention-days: 1
+
+  quarto:
+    needs: execute
+    runs-on: ubuntu-latest
+    # store success output flag for the ci job
+    outputs:
+      success: ${{ steps.setoutput.outputs.success }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Download notebooks
+        uses: actions/download-artifact@v3
+        with:
+          name: notebooks
+          path: out/
+      - name: Display structure of downloaded files
+        run: ls -R
+        working-directory: out
+      - name: Copy back built notebooks
+        run: cp --verbose -rf out/docs/* docs/
       - name: Setup Quarto
         uses: quarto-dev/quarto-actions/setup@v2
       - name: Render Quarto Project
@@ -85,10 +94,32 @@ jobs:
         if: ${{ github.ref == 'refs/heads/main' }}
         with:
           path: _site
+      - name: Set output flag
+        id: setoutput
+        run: echo "success=true" >> $GITHUB_OUTPUT
+  # CI conclusion for GitHub status check
+  # https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
+  CI:
+    needs: quarto
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+      # pass step only when output of previous jupyter-book job is set
+      # in case at least one of the execution fails, jupyter-book is skipped
+      # and the output will not be set, which will then cause the ci job to fail
+      - run: |
+          passed="${{ needs.quarto.outputs.success }}"
+          if [[ $passed == "true" ]]; then
+            echo "Tests passed"
+            exit 0
+          else
+            echo "Tests failed"
+            exit 1
+          fi
 
   deploy:
     name: Deploy to GitHub pages
-    needs: CI
+    needs: quarto
     if: ${{ github.ref == 'refs/heads/main'}}
     # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
     permissions:
